services:
  app:
    container_name: escape-room-app
    build: .
    ports:
      - "3000:3000"    # WEB Next.js
      - "5555:5555"    # Prisma Studio
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    volumes:
      - sqlite_data:/app/prisma   # simpan DB supaya tidak hilang
    restart: always

volumes:
  sqlite_data:
