version: "3.9"

services:
  app:
    container_name: assignment-nextapp-1
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"   # untuk Prisma Studio
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/assignment?schema=public"
    depends_on:
      - db
    networks:
      - assignment-net

  db:
    container_name: assignment-db-1
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: assignment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - assignment-net

networks:
  assignment-net:

volumes:
  postgres_data:
